/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Indri {

using System;
using System.Runtime.InteropServices;

public class AttributeValuePair : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal AttributeValuePair(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(AttributeValuePair obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~AttributeValuePair() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          indri_csharpPINVOKE.delete_AttributeValuePair(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string attribute {
    set {
      indri_csharpPINVOKE.AttributeValuePair_attribute_set(swigCPtr, value);
    } 
    get {
      string ret = indri_csharpPINVOKE.AttributeValuePair_attribute_get(swigCPtr);
      return ret;
    } 
  }

  public string value {
    set {
      indri_csharpPINVOKE.AttributeValuePair_value_set(swigCPtr, value);
    } 
    get {
      string ret = indri_csharpPINVOKE.AttributeValuePair_value_get(swigCPtr);
      return ret;
    } 
  }

  public uint begin {
    set {
      indri_csharpPINVOKE.AttributeValuePair_begin_set(swigCPtr, value);
    } 
    get {
      uint ret = indri_csharpPINVOKE.AttributeValuePair_begin_get(swigCPtr);
      return ret;
    } 
  }

  public uint end {
    set {
      indri_csharpPINVOKE.AttributeValuePair_end_set(swigCPtr, value);
    } 
    get {
      uint ret = indri_csharpPINVOKE.AttributeValuePair_end_get(swigCPtr);
      return ret;
    } 
  }

  public AttributeValuePair() : this(indri_csharpPINVOKE.new_AttributeValuePair(), true) {
  }

}

}
