/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Indri {

using System;
using System.Runtime.InteropServices;

public class DocumentVectorVector : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IList<DocumentVector>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DocumentVectorVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(DocumentVectorVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~DocumentVectorVector() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      for (int i=0; i<Count; i++) {
        indri_csharpPINVOKE.delete_DocumentVector(DocumentVector.getCPtr(getitem(i)));
    }        
      indri_csharpPINVOKE.delete_DocumentVectorVector(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public DocumentVectorVector(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (DocumentVector element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public DocumentVector this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(DocumentVector[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(DocumentVector[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, DocumentVector[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<DocumentVector> System.Collections.Generic.IEnumerable<DocumentVector>.GetEnumerator() {
    return new DocumentVectorVectorEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new DocumentVectorVectorEnumerator(this);
  }

  public DocumentVectorVectorEnumerator GetEnumerator() {
    return new DocumentVectorVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class DocumentVectorVectorEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<DocumentVector>
#endif
  {
    private DocumentVectorVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public DocumentVectorVectorEnumerator(DocumentVectorVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public DocumentVector Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (DocumentVector)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    indri_csharpPINVOKE.DocumentVectorVector_Clear(swigCPtr);
  }

  public void Add(DocumentVector x) {
    indri_csharpPINVOKE.DocumentVectorVector_Add(swigCPtr, DocumentVector.getCPtr(x));
  }

  private uint size() {
    uint ret = indri_csharpPINVOKE.DocumentVectorVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = indri_csharpPINVOKE.DocumentVectorVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    indri_csharpPINVOKE.DocumentVectorVector_reserve(swigCPtr, n);
  }

  public DocumentVectorVector() : this(indri_csharpPINVOKE.new_DocumentVectorVector__SWIG_0(), true) {
  }

  public DocumentVectorVector(DocumentVectorVector other) : this(indri_csharpPINVOKE.new_DocumentVectorVector__SWIG_1(DocumentVectorVector.getCPtr(other)), true) {
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public DocumentVectorVector(int capacity) : this(indri_csharpPINVOKE.new_DocumentVectorVector__SWIG_2(capacity), true) {
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  private DocumentVector getitemcopy(int index) {
    IntPtr cPtr = indri_csharpPINVOKE.DocumentVectorVector_getitemcopy(swigCPtr, index);
    DocumentVector ret = (cPtr == IntPtr.Zero) ? null : new DocumentVector(cPtr, false);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private DocumentVector getitem(int index) {
    IntPtr cPtr = indri_csharpPINVOKE.DocumentVectorVector_getitem(swigCPtr, index);
    DocumentVector ret = (cPtr == IntPtr.Zero) ? null : new DocumentVector(cPtr, false);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, DocumentVector val) {
    indri_csharpPINVOKE.DocumentVectorVector_setitem(swigCPtr, index, DocumentVector.getCPtr(val));
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(DocumentVectorVector values) {
    indri_csharpPINVOKE.DocumentVectorVector_AddRange(swigCPtr, DocumentVectorVector.getCPtr(values));
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public DocumentVectorVector GetRange(int index, int count) {
    IntPtr cPtr = indri_csharpPINVOKE.DocumentVectorVector_GetRange(swigCPtr, index, count);
    DocumentVectorVector ret = (cPtr == IntPtr.Zero) ? null : new DocumentVectorVector(cPtr, true);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, DocumentVector x) {
    indri_csharpPINVOKE.DocumentVectorVector_Insert(swigCPtr, index, DocumentVector.getCPtr(x));
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, DocumentVectorVector values) {
    indri_csharpPINVOKE.DocumentVectorVector_InsertRange(swigCPtr, index, DocumentVectorVector.getCPtr(values));
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    indri_csharpPINVOKE.DocumentVectorVector_RemoveAt(swigCPtr, index);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    indri_csharpPINVOKE.DocumentVectorVector_RemoveRange(swigCPtr, index, count);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public static DocumentVectorVector Repeat(DocumentVector value, int count) {
    IntPtr cPtr = indri_csharpPINVOKE.DocumentVectorVector_Repeat(DocumentVector.getCPtr(value), count);
    DocumentVectorVector ret = (cPtr == IntPtr.Zero) ? null : new DocumentVectorVector(cPtr, true);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    indri_csharpPINVOKE.DocumentVectorVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    indri_csharpPINVOKE.DocumentVectorVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, DocumentVectorVector values) {
    indri_csharpPINVOKE.DocumentVectorVector_SetRange(swigCPtr, index, DocumentVectorVector.getCPtr(values));
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(DocumentVector value) {
    bool ret = indri_csharpPINVOKE.DocumentVectorVector_Contains(swigCPtr, DocumentVector.getCPtr(value));
    return ret;
  }

  public int IndexOf(DocumentVector value) {
    int ret = indri_csharpPINVOKE.DocumentVectorVector_IndexOf(swigCPtr, DocumentVector.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(DocumentVector value) {
    int ret = indri_csharpPINVOKE.DocumentVectorVector_LastIndexOf(swigCPtr, DocumentVector.getCPtr(value));
    return ret;
  }

  public bool Remove(DocumentVector value) {
    bool ret = indri_csharpPINVOKE.DocumentVectorVector_Remove(swigCPtr, DocumentVector.getCPtr(value));
    return ret;
  }

}

}
