/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Indri {

using System;
using System.Runtime.InteropServices;

public class Field : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Field(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Field obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Field() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          indri_csharpPINVOKE.delete_Field(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public string name {
    set {
      indri_csharpPINVOKE.Field_name_set(swigCPtr, value);
      if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = indri_csharpPINVOKE.Field_name_get(swigCPtr);
      if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public int begin {
    set {
      indri_csharpPINVOKE.Field_begin_set(swigCPtr, value);
    } 
    get {
      int ret = indri_csharpPINVOKE.Field_begin_get(swigCPtr);
      return ret;
    } 
  }

  public int end {
    set {
      indri_csharpPINVOKE.Field_end_set(swigCPtr, value);
    } 
    get {
      int ret = indri_csharpPINVOKE.Field_end_get(swigCPtr);
      return ret;
    } 
  }

  public long number {
    set {
      indri_csharpPINVOKE.Field_number_set(swigCPtr, value);
    } 
    get {
      long ret = indri_csharpPINVOKE.Field_number_get(swigCPtr);
      return ret;
    } 
  }

  public int ordinal {
    set {
      indri_csharpPINVOKE.Field_ordinal_set(swigCPtr, value);
    } 
    get {
      int ret = indri_csharpPINVOKE.Field_ordinal_get(swigCPtr);
      return ret;
    } 
  }

  public int parentOrdinal {
    set {
      indri_csharpPINVOKE.Field_parentOrdinal_set(swigCPtr, value);
    } 
    get {
      int ret = indri_csharpPINVOKE.Field_parentOrdinal_get(swigCPtr);
      return ret;
    } 
  }

  public Field() : this(indri_csharpPINVOKE.new_Field(), true) {
  }

}

}
