/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_indri_csharp_WRAP_H_
#define SWIG_indri_csharp_WRAP_H_

struct SwigDirector_IndexStatus : public indri::api::IndexStatus, public Swig::Director {

public:
    SwigDirector_IndexStatus();
    virtual ~SwigDirector_IndexStatus();
    virtual void status(int code, std::string const &documentPath, std::string const &error, int documentsIndexed, int documentsSeen);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int, char *, char *, int, int);
    void swig_connect_director(SWIG_Callback0_t callbackstatus);

private:
    SWIG_Callback0_t swig_callbackstatus;
    void swig_init_callbacks();
};


#endif
