/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Indri {

using System;
using System.Runtime.InteropServices;

public class Parameters : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Parameters(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(Parameters obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~Parameters() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          indri_csharpPINVOKE.delete_Parameters(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public Parameters() : this(indri_csharpPINVOKE.new_Parameters(), true) {
  }

  public bool get(string name, bool def) {
    bool ret = indri_csharpPINVOKE.Parameters_get__SWIG_0(swigCPtr, name, def);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int get(string name, int def) {
    int ret = indri_csharpPINVOKE.Parameters_get__SWIG_1(swigCPtr, name, def);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public double get(string name, double def) {
    double ret = indri_csharpPINVOKE.Parameters_get__SWIG_2(swigCPtr, name, def);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public long get(string name, long def) {
    long ret = indri_csharpPINVOKE.Parameters_get__SWIG_3(swigCPtr, name, def);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string get(string name, string def) {
    string ret = indri_csharpPINVOKE.Parameters_get__SWIG_4(swigCPtr, name, def);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void remove(string path) {
    indri_csharpPINVOKE.Parameters_remove(swigCPtr, path);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set(string name, bool value) {
    indri_csharpPINVOKE.Parameters_set__SWIG_0(swigCPtr, name, value);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set(string name, string value) {
    indri_csharpPINVOKE.Parameters_set__SWIG_1(swigCPtr, name, value);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set(string name, int value) {
    indri_csharpPINVOKE.Parameters_set__SWIG_2(swigCPtr, name, value);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set(string name, long value) {
    indri_csharpPINVOKE.Parameters_set__SWIG_3(swigCPtr, name, value);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set(string name, double value) {
    indri_csharpPINVOKE.Parameters_set__SWIG_4(swigCPtr, name, value);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void set(string value) {
    indri_csharpPINVOKE.Parameters_set__SWIG_5(swigCPtr, value);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void clear() {
    indri_csharpPINVOKE.Parameters_clear(swigCPtr);
  }

  public uint size() {
    uint ret = indri_csharpPINVOKE.Parameters_size(swigCPtr);
    return ret;
  }

  public bool exists(int index) {
    bool ret = indri_csharpPINVOKE.Parameters_exists__SWIG_0(swigCPtr, index);
    return ret;
  }

  public bool exists(string name) {
    bool ret = indri_csharpPINVOKE.Parameters_exists__SWIG_1(swigCPtr, name);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void load(string text) {
    indri_csharpPINVOKE.Parameters_load(swigCPtr, text);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public static Parameters instance() {
    Parameters ret = new Parameters(indri_csharpPINVOKE.Parameters_instance(), false);
    return ret;
  }

}

}
