/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Indri {

using System;
using System.Runtime.InteropServices;

public class ParsedDocumentVector : IDisposable, System.Collections.IEnumerable
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IList<ParsedDocument>
#endif
 {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ParsedDocumentVector(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ParsedDocumentVector obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ParsedDocumentVector() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr.Handle != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      for (int i=0; i<Count; i++) {
        indri_csharpPINVOKE.delete_ParsedDocument(ParsedDocument.getCPtr(getitem(i)));
    }        
      indri_csharpPINVOKE.delete_ParsedDocumentVector(swigCPtr);
    }
    swigCPtr = new HandleRef(null, IntPtr.Zero);
    GC.SuppressFinalize(this);
  }

  public ParsedDocumentVector(System.Collections.ICollection c) : this() {
    if (c == null)
      throw new ArgumentNullException("c");
    foreach (ParsedDocument element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public ParsedDocument this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array)
#else
  public void CopyTo(ParsedDocument[] array)
#endif
  {
    CopyTo(0, array, 0, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(System.Array array, int arrayIndex)
#else
  public void CopyTo(ParsedDocument[] array, int arrayIndex)
#endif
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

#if SWIG_DOTNET_1
  public void CopyTo(int index, System.Array array, int arrayIndex, int count)
#else
  public void CopyTo(int index, ParsedDocument[] array, int arrayIndex, int count)
#endif
  {
    if (array == null)
      throw new ArgumentNullException("array");
    if (index < 0)
      throw new ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

#if !SWIG_DOTNET_1
  System.Collections.Generic.IEnumerator<ParsedDocument> System.Collections.Generic.IEnumerable<ParsedDocument>.GetEnumerator() {
    return new ParsedDocumentVectorEnumerator(this);
  }
#endif

  System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator() {
    return new ParsedDocumentVectorEnumerator(this);
  }

  public ParsedDocumentVectorEnumerator GetEnumerator() {
    return new ParsedDocumentVectorEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class ParsedDocumentVectorEnumerator : System.Collections.IEnumerator
#if !SWIG_DOTNET_1
    , System.Collections.Generic.IEnumerator<ParsedDocument>
#endif
  {
    private ParsedDocumentVector collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public ParsedDocumentVectorEnumerator(ParsedDocumentVector collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public ParsedDocument Current {
      get {
        if (currentIndex == -1)
          throw new InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new InvalidOperationException("Collection modified.");
        return (ParsedDocument)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new InvalidOperationException("Collection modified.");
      }
    }

#if !SWIG_DOTNET_1
    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
#endif
  }

  public void Clear() {
    indri_csharpPINVOKE.ParsedDocumentVector_Clear(swigCPtr);
  }

  public void Add(ParsedDocument x) {
    indri_csharpPINVOKE.ParsedDocumentVector_Add(swigCPtr, ParsedDocument.getCPtr(x));
  }

  private uint size() {
    uint ret = indri_csharpPINVOKE.ParsedDocumentVector_size(swigCPtr);
    return ret;
  }

  private uint capacity() {
    uint ret = indri_csharpPINVOKE.ParsedDocumentVector_capacity(swigCPtr);
    return ret;
  }

  private void reserve(uint n) {
    indri_csharpPINVOKE.ParsedDocumentVector_reserve(swigCPtr, n);
  }

  public ParsedDocumentVector() : this(indri_csharpPINVOKE.new_ParsedDocumentVector__SWIG_0(), true) {
  }

  public ParsedDocumentVector(ParsedDocumentVector other) : this(indri_csharpPINVOKE.new_ParsedDocumentVector__SWIG_1(ParsedDocumentVector.getCPtr(other)), true) {
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public ParsedDocumentVector(int capacity) : this(indri_csharpPINVOKE.new_ParsedDocumentVector__SWIG_2(capacity), true) {
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  private ParsedDocument getitemcopy(int index) {
    IntPtr cPtr = indri_csharpPINVOKE.ParsedDocumentVector_getitemcopy(swigCPtr, index);
    ParsedDocument ret = (cPtr == IntPtr.Zero) ? null : new ParsedDocument(cPtr, false);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private ParsedDocument getitem(int index) {
    IntPtr cPtr = indri_csharpPINVOKE.ParsedDocumentVector_getitem(swigCPtr, index);
    ParsedDocument ret = (cPtr == IntPtr.Zero) ? null : new ParsedDocument(cPtr, false);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, ParsedDocument val) {
    indri_csharpPINVOKE.ParsedDocumentVector_setitem(swigCPtr, index, ParsedDocument.getCPtr(val));
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(ParsedDocumentVector values) {
    indri_csharpPINVOKE.ParsedDocumentVector_AddRange(swigCPtr, ParsedDocumentVector.getCPtr(values));
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public ParsedDocumentVector GetRange(int index, int count) {
    IntPtr cPtr = indri_csharpPINVOKE.ParsedDocumentVector_GetRange(swigCPtr, index, count);
    ParsedDocumentVector ret = (cPtr == IntPtr.Zero) ? null : new ParsedDocumentVector(cPtr, true);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, ParsedDocument x) {
    indri_csharpPINVOKE.ParsedDocumentVector_Insert(swigCPtr, index, ParsedDocument.getCPtr(x));
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, ParsedDocumentVector values) {
    indri_csharpPINVOKE.ParsedDocumentVector_InsertRange(swigCPtr, index, ParsedDocumentVector.getCPtr(values));
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    indri_csharpPINVOKE.ParsedDocumentVector_RemoveAt(swigCPtr, index);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    indri_csharpPINVOKE.ParsedDocumentVector_RemoveRange(swigCPtr, index, count);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public static ParsedDocumentVector Repeat(ParsedDocument value, int count) {
    IntPtr cPtr = indri_csharpPINVOKE.ParsedDocumentVector_Repeat(ParsedDocument.getCPtr(value), count);
    ParsedDocumentVector ret = (cPtr == IntPtr.Zero) ? null : new ParsedDocumentVector(cPtr, true);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    indri_csharpPINVOKE.ParsedDocumentVector_Reverse__SWIG_0(swigCPtr);
  }

  public void Reverse(int index, int count) {
    indri_csharpPINVOKE.ParsedDocumentVector_Reverse__SWIG_1(swigCPtr, index, count);
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, ParsedDocumentVector values) {
    indri_csharpPINVOKE.ParsedDocumentVector_SetRange(swigCPtr, index, ParsedDocumentVector.getCPtr(values));
    if (indri_csharpPINVOKE.SWIGPendingException.Pending) throw indri_csharpPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(ParsedDocument value) {
    bool ret = indri_csharpPINVOKE.ParsedDocumentVector_Contains(swigCPtr, ParsedDocument.getCPtr(value));
    return ret;
  }

  public int IndexOf(ParsedDocument value) {
    int ret = indri_csharpPINVOKE.ParsedDocumentVector_IndexOf(swigCPtr, ParsedDocument.getCPtr(value));
    return ret;
  }

  public int LastIndexOf(ParsedDocument value) {
    int ret = indri_csharpPINVOKE.ParsedDocumentVector_LastIndexOf(swigCPtr, ParsedDocument.getCPtr(value));
    return ret;
  }

  public bool Remove(ParsedDocument value) {
    bool ret = indri_csharpPINVOKE.ParsedDocumentVector_Remove(swigCPtr, ParsedDocument.getCPtr(value));
    return ret;
  }

}

}
