/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace Indri {

using System;
using System.Runtime.InteropServices;

public class ScoredExtentResult : IDisposable {
  private HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ScoredExtentResult(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new HandleRef(this, cPtr);
  }

  internal static HandleRef getCPtr(ScoredExtentResult obj) {
    return (obj == null) ? new HandleRef(null, IntPtr.Zero) : obj.swigCPtr;
  }

  ~ScoredExtentResult() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          indri_csharpPINVOKE.delete_ScoredExtentResult(swigCPtr);
        }
        swigCPtr = new HandleRef(null, IntPtr.Zero);
      }
      GC.SuppressFinalize(this);
    }
  }

  public double score {
    set {
      indri_csharpPINVOKE.ScoredExtentResult_score_set(swigCPtr, value);
    } 
    get {
      double ret = indri_csharpPINVOKE.ScoredExtentResult_score_get(swigCPtr);
      return ret;
    } 
  }

  public int document {
    set {
      indri_csharpPINVOKE.ScoredExtentResult_document_set(swigCPtr, value);
    } 
    get {
      int ret = indri_csharpPINVOKE.ScoredExtentResult_document_get(swigCPtr);
      return ret;
    } 
  }

  public int begin {
    set {
      indri_csharpPINVOKE.ScoredExtentResult_begin_set(swigCPtr, value);
    } 
    get {
      int ret = indri_csharpPINVOKE.ScoredExtentResult_begin_get(swigCPtr);
      return ret;
    } 
  }

  public int end {
    set {
      indri_csharpPINVOKE.ScoredExtentResult_end_set(swigCPtr, value);
    } 
    get {
      int ret = indri_csharpPINVOKE.ScoredExtentResult_end_get(swigCPtr);
      return ret;
    } 
  }

  public long number {
    set {
      indri_csharpPINVOKE.ScoredExtentResult_number_set(swigCPtr, value);
    } 
    get {
      long ret = indri_csharpPINVOKE.ScoredExtentResult_number_get(swigCPtr);
      return ret;
    } 
  }

  public int ordinal {
    set {
      indri_csharpPINVOKE.ScoredExtentResult_ordinal_set(swigCPtr, value);
    } 
    get {
      int ret = indri_csharpPINVOKE.ScoredExtentResult_ordinal_get(swigCPtr);
      return ret;
    } 
  }

  public int parentOrdinal {
    set {
      indri_csharpPINVOKE.ScoredExtentResult_parentOrdinal_set(swigCPtr, value);
    } 
    get {
      int ret = indri_csharpPINVOKE.ScoredExtentResult_parentOrdinal_get(swigCPtr);
      return ret;
    } 
  }

  public ScoredExtentResult() : this(indri_csharpPINVOKE.new_ScoredExtentResult(), true) {
  }

}

}
