BEGIN { 
  print "// ";
  print "// Warning: This file is automatically generated";
  print "// ";
  print "";
  print "#include \"indri/Copier.hpp\"";
  print "#include \"indri/QuerySpec.hpp\"";
  print "";
  print "namespace indri { ";
  print "  namespace lang { ";
  print "    Copier::~Copier() {}";
  print "";
  print "    void Copier::defaultBefore( class Node* oldNode ) {}";
  print "    Node* Copier::defaultAfter( class Node* oldNode, class Node* newNode ) { return newNode; }";
  print "";
}

"class" == $1 {
  printf "    void Copier::before( class %s* oldNode ) { defaultBefore( oldNode ); }\n", $2;
  printf "    Node* Copier::after( class %s* oldNode, class %s* newNode ) { return defaultAfter( oldNode, newNode ); }\n", $2, $2;
}

END {
  print " }";
  print "}";
  print "";
}

