BEGIN { 
  print "// ";
  print "// Warning: This file is automatically generated";
  print "// ";
  print "";
  print "#include \"indri/Walker.hpp\"";
  print "#include \"indri/QuerySpec.hpp\"";
  print "";
  print "namespace indri { ";
  print "  namespace lang { ";
  print "    Walker::~Walker() {}";
  print "";
  print "    void Walker::defaultBefore( class Node* n ) {}";
  print "    void Walker::defaultAfter( class Node* n ) {}";
  print "";
}

"class" == $1 {
  printf "   void Walker::before( class %s* n ) { defaultBefore( n ); }\n", $2;
  printf "   void Walker::after( class %s* n ) { defaultAfter( n ); }\n", $2, $2;
}

END {
  print " }";
  print "}";
  print "";
}

