/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.0
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package lemurproject.indri;
import java.util.Map;
public class QueryExpander {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public QueryExpander(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(QueryExpander obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        indriJNI.delete_QueryExpander(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ScoredExtentResult[] runExpandedQuery(String originalQuery, int resultsRequested, boolean verbose) {
  return indriJNI.QueryExpander_runExpandedQuery__SWIG_0(swigCPtr, this, originalQuery, resultsRequested, verbose);
}

  public ScoredExtentResult[] runExpandedQuery(String originalQuery, int resultsRequested) {
  return indriJNI.QueryExpander_runExpandedQuery__SWIG_1(swigCPtr, this, originalQuery, resultsRequested);
}

  public String expand(String originalQuery, ScoredExtentResult[] results) {
    return indriJNI.QueryExpander_expand(swigCPtr, this, originalQuery, results);
  }

}
