BEGIN { 
  print "// ";
  print "// Warning: This file is automatically generated";
  print "// ";
  print "";
  print "#ifndef INDRI_COPIER_HPP";
  print "#define INDRI_COPIER_HPP";
  print "";
  print "namespace indri { ";
  print "  namespace lang { ";
  print "    class Copier { ";
  print "    public:";
  print "      virtual ~Copier();";
  print "      virtual void defaultBefore( class Node* oldNode );";
  print "      virtual class Node* defaultAfter( class Node* oldNode, class Node* newNode );";
  print "";
}

"class" == $1 {
  printf "      virtual void before( class %s* oldNode );\n", $2;
  printf "      virtual class Node* after( class %s* oldNode, class %s* newNode );\n", $2, $2;
}

END {
  print "   };";
  print " }";
  print "}";
  print "";
  print "#endif // INDRI_COPER_HPP";
  print "";
}

